microsoft/TypeScript-wiki

Basic-Types.md
Type-Compatibility.md

This pull-request unifies usage of semicolon in examples of enum. Enum doesn't need a semicolon, but some examples have them.
These semicolons make the readers think that a semicolon is required after enum. Such question was actually posted to TypeScripst's repository:
> [Const enum leaves behind semicolons · Issue #1685 · Microsoft/TypeScript](https://github.com/Microsoft/TypeScript/issues/1685)

Remove needless semicolons following enum.

---

API-Breaking-Changes.md

Fixing a typo concerning the inline code tag in the wiki; see diff.

Fix inline code tag

---

Roadmap.md

Aligns the roadmap with the official terms in the spec:
- *template strings* are now called *template literals*
- *tagged string templates* are now called *tagged templates*

Updates terms in roadmap to align with spec

---

TypeScript-Editor-Support.md

YATS is yet another TypeScript syntax file for Vim. It provides exuberant highlighting and a lot DOM keywords.

Add yats.vim to editor support

---

Contributing-to-TypeScript.md

As per this [comment](https://github.com/Microsoft/TypeScript/issues/4238#issuecomment-130068114) by @DanielRosenwasser I think we should put something related to
language and tone in the wiki section. How this sounds?

Language and Tone section in the wiki

---

Generics.md

A comment was left behind on a fixed example of how to use generics for parameter constraints.

Removing comment on fixed function

---

Dev-Mode-in-Visual-Studio.md

Updated the information about the registry settings for specifying the lib.d.ts library definition to use in conjunction with a custom language service file. These values are set using the PowerShell script, but were not included in the wiki page.

Updated registry information to include lib.d.ts

---

tsconfig.json.md

Trying to make it clear that this can be directories or files.
We recently implemented this in `grunt-ts`.  Even though all of the examples are with directory names, `exclude` can also accept file names and I wanted to make that clearer.

Improve documentation for exclude

---

Setting-Compiler-Options-in-MSBuild-projects.md

This fixes the documentation for using --isolatedModules with Visual Studio.  Also minor formatting changes.

--isolatedModules fix

---

Compiler-Options.md

Fixes [#4825](https://github.com/Microsoft/TypeScript/issues/4825) (from the original [**Microsoft / TypeScript**](https://github.com/Microsoft/TypeScript) repo).

Make command line option descriptions more consistent

---

Compiler-Options.md

Removed compiler flag --experimentalAsyncFunctions from wiki since it is removed for ts 1.7.x

Removed --experimentalAsyncFunctions

---

Compiler-Options.md

Fixed the typo in the '--mapRoot' session.

Fixed the typo in the --mapRoot session

---

Compiler-Options.md

I was reviewing the valid options and noticed that 'es6' wasn't listed. Passing an invalid module format to the compiler generates an error that lists the valid formats which include 'es6'.

added 'es6' as a valid option for the --module compiler option

---

Breaking-Changes.md

Under 1.5 > DOM interface changes, there was a period that should have been a comma.

Fixed period/comma typo in Breakin-Changes.md

---

What's-new-in-TypeScript.md

The code example for await/async waits for 200ms, while the comment above it mentions 400ms.

Typo in code description ("400ms" should be "200ms")

---

What's-new-in-TypeScript.md

There was a dangling quote that wasn't supposed to be there.

Remove extra quote

---

What's-new-in-TypeScript.md

Simple typo in the wiki WildChard should be Wildcard

Removed typo 'WildChard' and changed to 'Wildcard'

---

'this'-in-TypeScript.md

Previously this sounded as if it was ES5 only and not ES6.
I also added a link to the MDN for `Function.prototype.bind()`.

Make it clear that bind is ES5 or newer

---

Breaking-Changes.md

Documented breaking change for subclassing built-ins.

---

TypeScript-Editor-Support.md

typescript-tools.vim hasn't been updated into a couple of years.
Tsuquyomi is still active.
@DanielRosenwasser are you ok with this change? 
In addition, maybe on typescriptlang we should just have the Vim icon link to tsuquyomi because its README lists all the plugins you might want to install &mdash; better than our 1 paragraph.

Remove link to old vim plugin

---

Breaking-Changes.md

I am not sure, but I guess you meant: `!==`

Fix typo on literal types section

---

JSDoc-support-in-JavaScript.md

Fixed a few minor spelling and grammatical mistakes that I spotted in JSDoc-support-in-JavaScript.md.

Fixed typo in JSDoc-support-in-JavaScript.md

---

JSDoc-support-in-JavaScript.md

It took a while to figure out the syntax for defining a constructor parameter (or return type) in jsDoc notation, so I thought it was worth adding that to the docs.

Document how to define a constructor parameter

---

Using-the-Compiler-API.md

Without the space between `#` and `*`, this just looks like
> ##*Disclaimer*

Fix formatting in disclaimer

---

Coding-guidelines.md

Subgroups weren't showing up correctly.
Specifies curly braces for inline returns as optional

Fixed outline grouping and updated curly brace guidelines.

---

What's-new-in-TypeScript.md

use esnext to preserve  import expression

Dynamic import is not supported in ES2015

---

Type-Checking-JavaScript-Files.md

An `@augments` declaration was left in the to-be-undocumented snippet, and some declared arrays were not instantiated.

Correct some errors in JSDoc code

---

FAQ.md

Previously, the class was declared as `Bravo` but instantiated as `Beta`.

FAQ: Fix a `Beta`/`Bravo` inconsistency in an example

---

Roadmap.md

[#5579](https://github.com/Microsoft/TypeScript/issues/5579) is listed under "Future", but it will be resolved by [#15473](https://github.com/Microsoft/TypeScript/issues/15473), which is listed under 2.7.

Delete item from Future which is resolved in 2.7

---

FAQ.md

@mhegazy gave me some useful information about how to track down mistakes in `exclude`, which I think is useful enough to be added here.
https://github.com/Microsoft/TypeScript/issues/19798#issuecomment-342396496

Improve `exclude` documentation

---

FAQ.md

I pasted the isReallyInstanceOf<T> function into my editor and TypeScript (version 2.6.1) immediately caught two errors in the function signature:
> A rest parameter must be of an array type.
`{ ctor: { new(...args: any) => T }` -> `{ ctor: { new(...args: any[]) => T }`
> ':' expected.
`{ ctor: { new(...args: any[]) => T }` -> `{ ctor: { new(...args: any[]): T }`

Correct signature of isReallyInstanceOf

---

Debugging-Language-Service-in-VS-Code.md

This commit fixes the following deprecation:
DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.

Change node --debug to node --inspect

---

Using-the-Compiler-API.md

@mhegazy @sheetalkamat can you review this?

Provide an example of the watcher API

---

TypeScript-Editor-Support.md

Although nvim-typescript is mainly focused for nvim usage it can be also used for Vim 8 according to its [requierements](https://github.com/Shougo/deoplete.nvim#requirements)

Add nvim-typescript as an option for Vim 8

---

Breaking-Changes.md
FAQ.md
Using-the-Compiler-API.md
What's-new-in-TypeScript.md
Writing-a-Language-Service-Plugin.md

Max-width is set to 84, since that is what github pages can handle best.
See: https://github.com/Microsoft/TypeScript-wiki/issues/176
I mostly did the new relevant docs and also deleted trailing spaces (vscode did that for me, hope that's okay).

Use prettier for code examples that have a too long width

---

JSDoc-support-in-JavaScript.md

The default `Element` type shows errors for common dom attributes. This PR adds a doc for declaring an explicit `HTMLElement` type.

Add html element example

---

JSDoc-support-in-JavaScript.md

TypeScript actually does support using `T | null` in JSDoc types with `strictNullChecks: true`.
review?(@sandersn)

docs(jsdoc): Document union nullable types

---

JSDoc-support-in-JavaScript.md

Here shows the right syntax and mis-spelled version

fix jsdoc @typedef annotation order error

---

API-Breaking-Changes.md

As you can see, one link was missing and another was a bare URL.
As for the wording tweak, data suggests that "case per case" [peaked around 1930][ngram1] and [has never come near "case by case"][ngram2].
[ngram1]: https://books.google.com/ngrams/graph?content=case+per+case&case_insensitive=on&year_start=1920&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Ccase%20per%20case%3B%2Cc0
[ngram2]: https://books.google.com/ngrams/graph?content=case+per+case%2C+case+by+case&case_insensitive=on&year_start=1920&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Ccase%20per%20case%3B%2Cc0%3B.t4%3B%2Ccase%20by%20case%3B%2Cc0%3B%2Cs0%3B%3Bcase%20by%20case%3B%2Cc0%3B%3BCase%20by%20case%3B%2Cc0#t1%3B%2Ccase%20per%20case%3B%2Cc0%3B.t4%3B%2Ccase%20by%20case%3B%2Cc0%3B%2Cs1%3B%3Bcase …

API-Breaking-Changes: fix PR links, tweak wording

---

JSDoc-support-in-JavaScript.md

Opened on request of @brettz9 in https://github.com/jsdoctypeparser/jsdoctypeparser/issues/50#issuecomment-480556815.
See also https://github.com/Microsoft/TypeScript/issues/7237
review?(@sandersn)

docs(jsdoc): Document unsupported JSDoc tags with open issues

---

JavaScript-Language-Service-in-Visual-Studio.md

The original declaration files link was dead, and the page it had been pointing to now refers us to the `declaration files/Introduction.md`. This will fix the issue mentioned in issue #28484 of the main TS repository.

Fixes broken link

---

JSDoc-support-in-JavaScript.md

The JSDoc-support-in-JavaScript file doesn't contain information on classes at all, so I added the information I do know.

Improve JSDoc documentation for ES6 classes

---

JavaScript-Language-Service-in-Visual-Studio.md

1. The link for JSDoc support was directing the user to an empty page. Fixed.

Fixed broken link for JSDoc support.

---

FAQ.md

As of [version 2.2](https://devblogs.microsoft.com/typescript/announcing-typescript-2-2/), it is no longer accurate.

Remove outdated & incorrect section on string indexers

---

Debugging-Language-Service-in-VS-Code.md

The `request` shall be `attach`.

fix mistaken launch.json example for debugging tsserver

---

FAQ.md

The code sample in [you should emit classes like this so they have real private members FAQ](https://github.com/microsoft/TypeScript/wiki/FAQ#you-should-emit-classes-like-this-so-they-have-real-private-members) is incorrect, it "shows" that instantiating a new `Foo()` would reset the private `x` of `a` which is not True, in fact that is not what happens:
```
> var Foo = (function () {
...     var x = 0;
...
...     function Foo() {
...     }
...     Foo.prototype.increment = function () {
...         x++;
...         return x;
...     };
...     return Foo;
... })();
undefined
> var a = new Foo();
undefined
> a.increment();
1
> a.increment();
2
> var b = new Foo();
undefined
> a.increment();
3
```
But it is true that `a` and `b` use the same `x` and therefore one influences the other. …

Fix incorrect code sample in "Things that don't work" section of FAQ

---

Standalone-Server-(tsserver).md

Tiny docs change to avoid confusion.  `tsserver` doesn't seem to mind this bad example as it defers to the command.

Change type in request example

---

Performance.md

At this point this is incomplete, but I'm looking for some feedback.
The current TODOs are
Things that I want feedback on
* page title and location (where do users find this?)
* what topics are we missing?
* what topics are superfluous?
* is the order correct? (e.g. should project structure come before discussion around project references?)

Initial write-up of performance best practices and diagnostics.

---

Home.md
_Sidebar.md
sync.bat

Starts a re-focus for the wiki with three main interests:
- Debugging TypeScript problems
- Using the compiler API
- Wanting to contribute to the TypeScript codebase

Initial work on re-framing the wiki

---

Roadmap.md

Adds 3.8 back to the Roadmap

---

Roadmap.md

**ES Private Fields** are now supported in TypeScript 3.8 and can be removed from Future list

Updated Roadmap (markdown)

---

Using-the-Compiler-API.md

The implementation of a LanguageServiceHost in the example is missing `directoryExists` and `getDirectories` methods which are crucial for the resolving `typeRoots` automatically in the function `ts.getAutomaticTypeDirectiveNames`.

Fix non-complete implementation of a language service

---

Using-the-Compiler-API.md

Before it always returned undefined for the type definition output

Fix bug in code example

---

Using-the-Language-Service-API.md

[Issue #1793](https://github.com/Microsoft/TypeScript/issues/1793) has been closed and the following pull request was merged, this is no longer needed.

Closed issue, part of the text no longer needed

---

Node-Target-Mapping.md

According to [node.green](https://node.green/), Node.js 14 has full support for ES2020
Closes #261

Add target mapping for Node.js 14

---

Writing-a-Language-Service-Plugin.md

Clarify the documentation on language service plugins for users who are unfamiliar with the fact that the typescript language service is not used by the `tsc` command.
Another case of confusion on this point: https://github.com/microsoft/TypeScript/issues/34548

Note `tsc` doesn't use language service plugins

---

Performance-Tracing.md
Performance.md

Mainly use a single `about://tracing` URL which works in both Edge and
Chrome.
Few other minor tweaks (including reducing the very long link texts).

Tracing tweaks

---

Useful-Links-for-TypeScript-Issue-Management.md

The `Needs More Info Review` link was incorrectly described as "issues tagged with `Needs Proposal`".

Fix typo in Useful-Links-for-TypeScript-Issue-Management.md

---

Using-the-Compiler-API.md

All examples tested with version 4.2.3. The correction I have made has also been tested with the current latest master branch source (https://github.com/microsoft/TypeScript/commit/ec77bff33226fb01f4e38b20e481f8c1fcd9e6c0).

Updated wiki example to match TypeScript 4.2.3

---

Performance-Tracing.md

It wasn't immediately clear to me that I would need
to use both `-p foo` and `--generateTrace foo`.

Add example command for --generateTrace

---

.github/workflows/sync
.github/workflows/sync.yml
README.md

> See also the [TS side](https://github.com/microsoft/TypeScript/pull/44207) of this PR.
Previously, changes to the wiki would get merged to the public repo in a
once-a-week action.  This significantly revises this, making the two
sides be mirrors (up to the few seconds it takes to do a merge).
This is driven by a minimal-ish yaml file in both sides (`TypeScript`
and `TypeScript-wiki`) that *always* works from the script in the public
repo.
The two action specs are nearly identical, but there are some differences:
- On the main repo, trigger on a `gollum` event, and in the wiki repo
the usual (pushes, schedule, manual).  (The schedule run is kept as
a just-in-case, and it's now running twice a week.)
- The filename is `sync-wiki` on the TS side and just `sync` in the
wiki.  (Good to avoid …

Implement a two-way mirroring between the wiki and its public repo

---

Node-Target-Mapping.md

Node.js 16 is LTS, but we don't have mapping at the wiki. This pull request should resolve this issue.

Add target mapping for Node.js 16

---

Writing-a-Language-Service-Plugin.md

Please allow me to add our language service plugin to the in the references section of the "Writing a Language Service Plugin" page.

Add language service plugin reference

---

Writing-a-Language-Service-Plugin.md

While creating our Language Service plugin we used this article as our main source. It was a huge help. Here are a few improvements so it can be of an even better help for the next person using it.
This PR does two small changes:
**Fix the "Decorator Creation" code example**
- Return `create` to the factory function instead to itself
- Return `proxy` to the `create` function
- Add `export = init;` to the end of the example
**Add a bit more context to the "Handling User Configuration" code example**
The combination of the bug in the "Decorator Creation" code example and this code example was confusing us. I think a little extra context will help the next person reading this.

Improve writing a language service plugin

---

Performance-Tracing.md
Performance.md

Advertise @typescript/analyze-trace and make the notes less specific to TS 4.1.

Update tracing instructions

---

Performance.md

Presently a large portion of the Performance document is concealed in a collapsible section due to an unclosed `<details>` tag.
[`details` in GitHub MarkDown](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)

Fix Performance dropdown closing </details> tag

---

TypeScript-Editor-Support.md

The plugin [nvim-typescript](https://github.com/mhartington/nvim-typescript) is deprecated since there is a [built-in LSP client](https://neovim.io/doc/user/lsp.html) in NeoVim since version 0.5. This commit updates the TypeScript Editor Support page with this information.

Updated description of NeoVim support

---

API-Breaking-Changes.md

https://nodejs.org/en/blog/release/v14.15.0

Fix Node.js 14 EOL date

---

Standalone-Server-(tsserver).md

Micro-fix. Link out to `CommandTypes` was broken. Decided to link to the source code

Use non-broken link to protocol/commandTypes

---

Using-the-Compiler-API.md

Fixes https://github.com/microsoft/TypeScript/issues/55760. I know that that issue hasn't been accepted but I think these docs are very useful.

Added 'Type Checker APIs' section prefix to type checker docs

---

Writing-a-Language-Service-Plugin.md

The `styled-components` plugin was moved. TSLint is deprecated. Astro, MDX, Vue, and Svelte now provide TypeScript plugins.

Update the TypeScript Real-world plugins list

---

FAQ.md

Fixes https://github.com/microsoft/TypeScript-wiki/issues/339

Fix: typo in FAQ.md file

---

FAQ.md

As suggested by https://github.com/microsoft/TypeScript/pull/58296#issuecomment-2617028921.

`--enforceReadonly` has not yet been released

---

Node-Target-Mapping.md

Updated the Node Target Mapping page based on https://github.com/tsconfig/bases/.
The related PR for the `nodenext` note is https://github.com/tsconfig/bases/pull/301

Update Node Target Mapping based on tsconfig bases
