Using-the-Compiler-API.md

Changed the definitions from the 1.4 version to 1.5

Changed definitions version to 1.5

---

Breaking-Changes.md

Found this when trying 1.5 . Caused a problem with auth0.

Updated Breaking Changes (markdown)

---

JSX.md
_Sidebar.md

@RyanCavanaugh asked if I could submit a PR for this based on my [blog entry](www.jbrantly.com/typescript-and-jsx/). I tried to de-editorialize it a bit from the original.
I also think @basarat did a good job summarizing in [his book](http://basarat.gitbooks.io/typescript/content/docs/jsx/tsx.html). His version is less wordy, might be able to incorporate some of those ideas here.

Add JSX page

---

Modules.md

While reading the wiki I noticed a small issue.

Fix header

---

tsconfig.json.md

Updates to tsconfig.json for the new 'excludes' property in TS1.6

Updates to tsconfig.json for the new 'exclude' property

---

Functions.md

Grammar fix

---

Functions.md

The word "when" was used twice very closely together, making the sentence slightly awkward to read.

Simplify a sentence

---

Architectural-Overview.md
Using-the-Compiler-API.md
Using-the-Language-Service-API.md

I fixed a couple small errors in the wiki pages.

Fixed misspelled words and small grammar issues

---

_Footer.md

It says "clone it and submit a PR".  This works for Microsoft folks, but the public technically has to fork it.

Improve footer

---

Setting-Compiler-Options-in-MSBuild-projects.md

Documents result of https://github.com/Microsoft/TypeScript/issues/5162

Aded JSX and documentation for Microsoft.TypeScript.targets

---

Architectural-Overview.md

Add the content from my reply in https://github.com/Microsoft/TypeScript/issues/5550#issuecomment-154573103 to the wiki.

Add compilation overview section

---

What's-new-in-TypeScript.md

Editing for the "What's new in TypeScript" page.

---

TypeScript-Editor-Support.md

Details : [alm.tools](http://alm.tools)

:memo: soft launched alm.tools

---

Compiler-Internals.md

@DanielRosenwasser @mhegazy can you take a look?

Add a bit more to Compiler Internals

---

Compiler-Internals.md

Addresses @DanielRosenwasser's comments that I missed in the previous PR.

Minor updates to Compiler Internals

---

FAQ.md

@RyanCavanaugh or @DanielRosenwasser can you take a look?
Also, a couple of the TOC links updated. Are there some parameters I'm supposed to pass to `doctoc`? I just used `doctoc FAQ.md`

FAQ: Access arbitrary properties w/string indexer

---

TypeScript-Editor-Support.md

Added a reference to the CATS IDE (an IDE written in TypeScript)

Updated TypeScript-Editor-Support.md

---

FAQ.md

And add a little advice about the TypeScript way to make nominal subclasses.
@RyanCavanaugh you wrote the original question. Can you take a look?

Elaborate on empty-class warning

---

Home.md

`withTypeScript` => `with TypeScript`

Add missing space

---

What's-new-in-TypeScript.md

Fixed typo in What's-new-in-TypeScript.md

---

FAQ.md

Basically the same as corresponding section on `Breaking-Change.md` with minor rewording.

fix #103, add extending native object to FAQ

---

FAQ.md

Addressed TODO at:
https://github.com/Microsoft/TypeScript-wiki/commit/ac7dfdc36a126318324654d071dfdc12e5ef0ef4#diff-e6f81a9d8df4fb4d787121a242ea6bf1R357
I don't feel particularly comfortable with my level of written English, so would appreciate any feedback about the phrasing (although I copied and pasted most of the content from the stackoverflow link).

Answer question about errors with index signature

---

Coding-guidelines.md

Change a run-on sentence into 2 sentences.

Fix comma splice.

---

Writing-a-Language-Service-Plugin.md

Hi. I'm loving TypeScript and Language Service Plugins.
I've developed https://github.com/Quramy/ts-graphql-plugin , would you put a link to this plugin?

Put a link to GraphQL plugin

---

Breaking-Changes.md
Coding-guidelines.md
FAQ.md
Nightly-drops.md
What's-new-in-TypeScript.md

Just doing some spell checking while scanning through the wiki

Typo fixes

---

Writing-a-Language-Service-Plugin.md

Add tslint language service as real-world Plugins

Add tslint language service as real-world Plugins

---

Using-the-Compiler-API.md

- Use @types/node
- Remove reference to typings/node/node.d.ts
- Compile with --strict
- Remove 1.4 note
- Fix https://github.com/Microsoft/TypeScript/issues/19148, by adding getDirectories

Update samples and Fix https://github.com/Microsoft/TypeScript/issues/19148

---

JSDoc-support-in-JavaScript.md
Type-Checking-JavaScript-Files.md

Document JS type assertions, update examples.

---

Writing-a-Language-Service-Plugin.md

Added notes/changed wording for a few pitfalls I fell in while going
through this guide, as well as updated the proxy code to be simpler and
avoid an assertion to ‘any’

Update the language service plugin docs

---

What's-new-in-TypeScript.md

Describe JSX fragment support in What's New

---

Using-the-Compiler-API.md

Noticed some typos when converting to the compiler

Fixes typos in Using-the-Compiler-API.md

---

Using-the-Compiler-API.md

had to lookup the source code to find this. I hope it'll help others too.
Thanks :)

Added link reference to ts.syntaxKind. I

---

Home.md

Fixes https://github.com/Microsoft/TypeScript/issues/25858

Update tutorials list

---

FAQ.md

Hello there, I spent some time reading the FAQ and found some improvement opportunities.
Here they are. Thanks for the wonderful write-up.

Fix typos and spelling in the TypeScript FAQ

---

Standalone-Server-(tsserver).md

Added a link to nvim-typescript for tsserver wiki page.

add nvim-typescript link in standalone server

---

Writing-a-Language-Service-Plugin.md

just want to add my package on

---

Using-the-Compiler-API.md

fixed some errors in the sample code. tested using v3.0.3

fixed broken sample code

---

FAQ.md

A few typo/grammar fixes and some minor proofreading. Hopefully, nothing too opinionated here.

Proofreading

---

Breaking-Changes.md

As per issue https://github.com/microsoft/TypeScript-wiki/issues/235

Correct "broken example"

---

Using-the-Compiler-API.md

Updates the "How to use the compiler API" section with
- Adds two new examples from things I've needed to build over the last 2 weeks
- How to make a DTS for a JS file
- How to re-print a particular top-level AST node
- Removes a duplicated section
- Manually formatted some of the code - 80 characters should not force a console.log to be 8 lines long, that's just unreadable

Improve the compiler API section

---

Standalone-Server-(tsserver).md

Fix typo in Standalone-Server-(tsserver).md

---

FAQ.md

I confess I didn't quite understand what that FAQ entry says :)

FAQ: Fix punctuation and formatting

---

Using-the-Compiler-API.md

This PR is created to address [this](https://github.com/microsoft/TypeScript-wiki/issues/275) issue.
I have updated the Typescript Compiler API functions as per Typescript version 4.1.3

Update example for Creating and Printing AST section in  Using-the-Compiler-API.md

---

Writing-a-Language-Service-Plugin.md

Add ts-string-literal-enum-plugin

---

FAQ.md

Line 1289 (How do I control file ordering in combined output?)
old: https://www.typescriptlang.org/docs/handbook/tsconfig.json.html 
new: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
Line 1237 (How do I write unit tests with typescript?)
old: https://basarat.gitbooks.io/typescript/docs/testing/jest.html
new: https://basarat.gitbook.io/typescript/intro-1/jest

Fixed 2 broken links in  FAQ.md

---

Performance.md

While reading the guide with an eye for improving the editor experience, I was not sure how ts-server behaves, or how fixing hotspots I view during tracing would change the editing experience. I ended up jumping into Discord for clarity, and this is a summary of what I learned.

Callout performance characteristics of ts-server

---

TypeScript's-Release-Process.md

Follows up on https://github.com/microsoft/TypeScript/issues/56396 here.

docs: added Bsky and Mastodon (Fosstodon) account mentions

---

.github/workflows/sync.yml

fix: usage of `node12 which is deprecated`

---

FAQ.md

docs: update FAQ.md
